[project]
name = "charity"
authors = []
description = ""
telemetry = false
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.charity-board]
path = "contracts/charity-board.clar"
depends_on = []
